/**
 * Comprehensive list of known ad networks, trackers, and analytics domains.
 * Used by the Island Dream proxy to strip ad-related elements from proxied pages.
 */
export const AD_DOMAINS: ReadonlySet<string> = new Set([
  // Google Ads & tracking
  "doubleclick.net",
  "googlesyndication.com",
  "googleadservices.com",
  "googletagmanager.com",
  "googletagservices.com",
  "google-analytics.com",
  "analytics.google.com",
  "adservice.google.com",
  "pagead2.googlesyndication.com",
  "ads.google.com",
  "adwords.google.com",
  "ssl.google-analytics.com",

  // Amazon Ads
  "amazon-adsystem.com",
  "assoc-amazon.com",
  "fls-na.amazon.com",

  // Facebook / Meta tracking
  "facebook.net",
  "connect.facebook.net",
  "an.facebook.com",
  "pixel.facebook.com",

  // Microsoft / Bing Ads
  "bat.bing.com",
  "ads.microsoft.com",
  "clarity.ms",
  "msads.net",
  "c.msn.com",

  // Twitter / X Ads
  "ads-twitter.com",
  "t.co",
  "static.ads-twitter.com",
  "analytics.twitter.com",

  // Programmatic ad networks
  "adnxs.com",           // AppNexus / Xandr
  "advertising.com",
  "pubmatic.com",
  "rubiconproject.com",
  "openx.net",
  "openx.com",
  "criteo.com",
  "criteo.net",
  "outbrain.com",
  "taboola.com",
  "taboolasyndication.com",
  "moatads.com",
  "moat.com",
  "mediamath.com",
  "bidswitch.net",
  "casalemedia.com",
  "contextweb.com",
  "demdex.net",
  "exelator.com",
  "turn.com",
  "tidaltv.com",
  "tradedesk.com",
  "thetradedesk.com",
  "indexww.com",
  "lijit.com",
  "sonobi.com",
  "sovrn.com",
  "triplelift.com",
  "sharethrough.com",
  "adsrvr.org",
  "adroll.com",
  "serving-sys.com",
  "mopub.com",
  "smartadserver.com",
  "smaato.com",
  "smaato.net",
  "inmobi.com",
  "mads.amazon-adsystem.com",
  "gravity.com",
  "undertone.com",
  "mathtag.com",
  "everesttech.net",
  "exoclick.com",
  "trafficjunky.net",
  "ero-advertising.com",
  "revcontent.com",
  "nativeads.com",
  "mgid.com",
  "adblade.com",
  "content.ad",

  // Analytics & heatmap trackers
  "scorecardresearch.com",
  "comscore.com",
  "quantserve.com",
  "chartbeat.com",
  "chartbeat.net",
  "hotjar.com",
  "static.hotjar.com",
  "script.hotjar.com",
  "vars.hotjar.com",
  "mixpanel.com",
  "api.mixpanel.com",
  "cdn.mxpnl.com",
  "segment.com",
  "segment.io",
  "cdn.segment.com",
  "api.segment.io",
  "amplitude.com",
  "api.amplitude.com",
  "cdn.amplitude.com",
  "fullstory.com",
  "rs.fullstory.com",
  "logrocket.com",
  "cdn.logrocket.com",
  "heapanalytics.com",
  "cdn.heapanalytics.com",
  "newrelic.com",
  "nr-data.net",
  "bam.nr-data.net",
  "dynatrace.com",
  "dynatracelabs.com",
  "dtm.demdex.net",

  // CRM / marketing automation trackers
  "pardot.com",
  "pi.pardot.com",
  "marketo.com",
  "munchkin.marketo.net",
  "hubspot.com",
  "js.hs-analytics.net",
  "js.hubspot.com",
  "track.hubspot.com",
  "forms.hubspot.com",
  "hs-banner.com",
  "hs-scripts.com",
  "hsleadflows.net",
  "hsadspixel.net",
  "intercom.io",
  "widget.intercom.io",
  "js.intercomcdn.com",
  "nexac.com",
  "eloqua.com",
  "edgekey.net",

  // Other trackers
  "addthis.com",
  "sharethis.com",
  "contentsquare.net",
  "contentsquare.com",
  "mouseflow.com",
  "luckyorange.com",
  "luckyorange.net",
  "inspectlet.com",
  "crazyegg.com",
  "clicktale.net",
  "clicktale.com",
  "clicky.com",
  "in.getclicky.com",
  "woopra.com",
  "statcounter.com",
  "histats.com",
  "onesignal.com",
  "cdn.onesignal.com",
  "spotxchange.com",
  "spotx.tv",
  "iponweb.com",
  "iponweb.net",
  "complexm.com",
  "adtech.de",
  "atwola.com",
  "2mdn.net",
  "admob.com",
  "doubleclick.net",
  "adcolony.com",
  "fyber.com",
  "mopub.com",
  "vungle.com",
  "applovin.com",
  "ironsrc.com",
  "supersonicads.com",
  "unity3d.com",  // Unity ads
  "unityads.unity3d.com",
  "chartboost.com",
  "flurry.com",
  "kochava.com",
  "appsflyer.com",
  "branch.io",
  "adjust.com",
  "singular.net",
]);

/**
 * Returns true if the given URL's hostname is a known ad/tracker domain
 * (or a subdomain of one).
 */
export function isAdDomain(url: string): boolean {
  try {
    const hostname = new URL(url).hostname.toLowerCase().replace(/^www\./, "");
    for (const domain of AD_DOMAINS) {
      if (hostname === domain || hostname.endsWith("." + domain)) {
        return true;
      }
    }
    return false;
  } catch {
    return false;
  }
}

/** Selectors for common ad container elements by class/id patterns */
export const AD_SELECTORS = [
  "[id*='google_ads']",
  "[id*='googletag']",
  "[class*='google-ad']",
  "[class*='GoogleAd']",
  "[id*='doubleclick']",
  "[class*='doubleclick']",
  "[data-ad-slot]",
  "[data-google-query-id]",
  "ins.adsbygoogle",
  "[id^='div-gpt-ad']",
  "[class*='adsbygoogle']",
  "[id*='taboola']",
  "[class*='taboola']",
  "[id*='outbrain']",
  "[class*='outbrain']",
  "[id*='adsense']",
  "[class*='adsense']",
  "[id*='ad-container']",
  "[id*='ad_container']",
  "[class*='ad-container']",
  "[id*='banner-ad']",
  "[class*='banner-ad']",
  "[id*='sponsor']",
  "[class*='sponsored-']",
  "[data-ad]",
  "iframe[src*='doubleclick']",
  "iframe[src*='googlesyndication']",
  "iframe[src*='googleadservices']",
  "iframe[src*='adnxs']",
  "iframe[src*='advertising']",
  "iframe[src*='taboola']",
  "iframe[src*='outbrain']",
  "iframe[id*='google_ads_iframe']",
].join(", ");
