// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/OrangePortraitEventPoster-Ix08NU/DeepOrangePoster.tsx": () => import("../components/mockups/templates/OrangePortraitEventPoster-Ix08NU/DeepOrangePoster.tsx")
};
